---
title: "GSMR"
author: "by [Yan Holtz](https://github.com/holtzy/) - `r format(Sys.time(), '%d %B %Y')`"
---



This part apply the [gsmr tool]("http://cnsgenomics.com/software/gsmr/") to our data


#- Data
GSMR needs:

- A risk factor GWAS summary statistics. This file has been created for diastolic pressure in the GWAS part
- GWAS summary statistics for diseases we want to explain. I'm gonna consider 23 diseases (ALLERGIC_RHINITIS ASTHMA CANCER CARD DEPRESS DERMATOPHYTOSIS DIA2 DYSLIPID HEMORRHOIDS HERNIA_ABDOMINOPELVIC HYPER INSOMNIA IRON_DEFICIENCY IRRITABLE_BOWEL MACDEGEN OSTIOA OSTIOP PEPTIC_ULCERS PSYCHIATRIC PVD STRESS SUM_DISEASES VARICOSE_VEINS). GWAS summary statistics [are available](http://cnsgenomics.com/data.html) for the UKB data + for the GERA consortium. I'm gonna use a meta analysis of these 2 datasets. I need to transfert these data from QBI cluster to delta:
```{bash, eval=FALSE}
# First transfert localy
cd /Users/y.holtz/Desktop
scp uqyholtz@inode.qbi.uq.edu.au://ibscratch/users/uqzzhu1/dataset/formatted_meta/combined_ukb_gera* .

# Then from locally to delta
cd /Users/y.holtz/Desktop
scp combined_ukb_gera* y.holtz@delta.imb.uq.edu.au://home/y.holtz/BLOOD_GWAS/0_DATA/EXTERNAL_GWAS_SUMSTAT
```


/ibscratch/users/uqzzhu1/code_project/gcta/build/gcta64

